### ISSUE TITLE
必要最低限の下準備

### ISSUE THREAD

**Issue by func-hs** [sogiSpk/Haskell_Introduction#1]
## はじめに

入門としての勉強会ということなので、以下の準備は最低限整えておいた方がいいでしょう。

* 日本語で書かれた参考書

プログラミングHaskell, すごいHaskell楽しく学ぼう など
必要に応じて回し読みできるだけの数は揃えておいた方がよいでしょう。

* 試しにコードを実行できる環境

発表者だけでも ghci とシェル環境を準備しておく必要があります。そうじゃないと、視聴者側は見せられたコードがどのような挙動や結果を返すのかイメージを得づらいということがありえます(実体験(させた方))

* 参考文献リンク集

視聴者が後々詳しい情報を調べる際の参考になります。

* 実践できるサイトないしサービスを探しておく

Atcoder, Codeforces, ProjectEuler などなど、問題として取り組めるものを探しておくとよいかもしれません。

**Comment by sogiSpk** [comment]
ありがとうございます。
反映させます。
