### ISSUE TITLE
発表内容を絞りましょう

### ISSUE THREAD

**Issue by func-hs** [sogiSpk/Haskell_Introduction#2]
## はじめに

サクッと文法等を見せただけではスムーズに行かないことが予想されます。なので、実用的な部分にあっさりと進まずに、ゆっくりと段階を踏んで馴染んでいってもらうのがいいと思います。左記を踏まえた上で指摘をしていきます。

## 現行案について

> 純粋関数型プログラミング言語

よく言われる呼び名ですが、最近は色々あって言葉自体が疑問視され始めています。後々所謂*マサカリ*が飛んでくることにもなりかねないので、現在の解釈や今どう呼ぶべきかなど、簡単にでも調べておいた方がよいです。(調べてもよくわからなければ敢えて使わずにおくのがベターです)

> 関数型言語と言えば～

同上。

> 言語の概要
> 言語の特徴

最初は発表内容をこれに特化した方が理解が進みやすい気がします。

> Parse(構文解析)が優秀

Haskell のコンパイラの話？それともパーサコンビネータライブラリの話？

> 参照透明性
> 遅延評価
> 静的片付け言語

これだけがすべてではないですよ！ていうかこれよりも Monad や型クラスやデータ型について説明し、それらの書き方を覚えてもらった方がいいかもしれません…(´･_･`)

> Haskellのコンパイラ
> GHC

今ではそれがデファクトスタンダードというだけで、(開発止まりかけてるのも含めれば)他のコンパイラもインタプリタも色々ありますよ。是非それらも合わせて教えてあげてください :)
(ideone や wandbox など、webの向こう側から結果を返してくれるサービスも紹介しておくとよいかと。どちらもHaskellに対応してます)

> 数学・物理の知識が乏しい

業務上必要にはなることと思いますが、まずは**言語仕様や基本構文を確実に覚えてもらうことに専念した方がよいでしょう。**少なくとも、Haskellを覚える上では必須ではないですし、逆に視聴者を混乱させる可能性があります。

> 使い道の難しさ
> ラムダ式など並行プログラミングに適しているらしいよ～

ラムダ式ではなく、基本的に再代入不可な仕組みによって、**他の上げられている手続き的かつ破壊的に書ける言語たち**よりかはそういったプログラミングをしやすいというのがよく言われていることです。また、Haskellの難しさというのは、(抽象的なプログラミング技法うんぬんは別として)以下の2つに集約されるのではないかと考えています。

* グラフィックプログラミング(OpenGL等)やGUI(Gtk等)の実装など、どうしても手続き的だったり破壊的だったりするようなことから切り離せない部分に対するアプローチの仕方
* 抽象度の高いデータ構造の定義と速度やメモリ消費量とのバランスのとり方

また、並行・並列処理を適切にコントロールしていくことの難しさはHaskellに限らず他のあらゆる言語でのプログラミングにも言えることです。

## 必ず教えておくべきこと

1. **Prelude にある head / tail / read の3つは、ああ見えて落とし穴があること**  
ここに書くと長くなるので、詳しくは可能な限り調べていただけると助かります。
2. **文字列(文字の List )を始めとした List 型のデータ構造と問題点**  
[GHCのこと](http://www.kotha.net/hperf/ghc.html)を一度ご覧になってから、文字と List それぞれのデータ構造と、それらが合わさった時のデータ構造を想像されると、それのメリットとデメリットがそれぞれ思い浮かぶと思います。また、文字列の問題点については、 tanakh 氏が過去に発表したスライド等にも記載されているので、検索してみてください。
3. **サンクについて(Haskellの遅延評価の落とし穴)**  
遅延評価の対象になっているデータは、どこかでパターンマッチが行われるまでスタックに残り続けます。そう遠くないタイミングでパターンマッチされるのであればよいのですが、放っておくと再帰呼び出しをしていく内にオーバーフロー(**スペースリーク**)します。これについても対処法も込みで説明しないと、原因不明のバグということで騒ぎになることが予想されます。
4. **末尾再帰最適化の話**  
必須ではないですが、割と重要です。
5. **計算を高速化したり、基本構文をある程度楽にしてくれるGHC拡張の紹介等**  
GADTs, OverloadedStrings, OverloadedLists, UnboxedTuples くらいは最低限話しておいた方がいいでしょう。

**Comment by func-hs** [comment]
https://github.com/sogiSpk/Haskell_Introduction/blob/master/Advance.md を見てて思ったのですが、札幌はHaskellなどに関して盛んな動きをしているわけではないですよ？
案件としても実際ゼロです。 XD

**Comment by muripoLife** [comment]
指摘ありがとうございます。
ググって出てきたので、書いてしまいました。
訂正します。

**Comment by func-hs** [comment]
## Basic.md への指摘

いくつか誤りが見つかったので書いておきますね。

### List

> 型がすべて同じ要素の組

まず**組ではない**です。(ここ大事)

> Javaなどのリストと同じ

JavaのどのListと同じということなのか存じていないのですが、記憶にある範囲であえて申し上げると…

* ArrayList

まず違います。Javaの`ArrayList`はあくまでもメモリの続く限り延長できる可変長配列です。

* LinkedList

次の要素へのポインタで繋がっているという点では共通している部分はありますが、同じと言い切れるかは微妙なところです。

### Tuple

> PHPの配列と同じ

違います。PHPの配列というのは、文字列もキーにできる連想配列です。対して、HaskellのTupleというのは複数の型のポインタの集合体です。[GHCのこと](http://www.kotha.net/hperf/ghc.html)をもう一度よく読んでみてくださいね :)

> タプル型 : ["ab", 1, false]

記法が間違っています。Tupleの記法は`("ab", 1, false)`などです。それと、Tupleは実装上の都合で**束縛できる要素数に限りがある**ので、お時間のよろしい時にGHCのライブラリのドキュメントなどを漁ってみてください。

### 多相型と型クラス

> 多相型
オブジェクト指向のジェネリックスに似た概念
例:legth [1,2,3,...,[int]]
legth ["a","aa",...,[String]]と、リストの中身は何でもいい

これも違います。ジェネリクスはあくまでも実際の型の"名前"をあと付けするためのものです。対してHaskellの多相型というのはどちらかといえば void ポインタに近いものです。引数に当てはめられたデータコンストラクタから型コンストラクタとその型引数を推論し、特定させます。
後、Listの中身はなんでもいいわけではなく、多相型であっても基本的には**型変数1つにつき1つの型のみあてはめられる**というのが大前提です。

> 多重定義型
オブジェクト指向のポルモフィズムに似た概念
引数の型が違うものでも、同じ関数名で複数関数を定義できる
例:abs [int]
   abs [Integer]

型クラスのメソッドは確かに多重定義を可能にしているものですが、通常の関数との違いも説明しておかないと、混乱を生じさせるかもしれません。

> 基本クラス（別名:型クラス）（オブジェクト指向言語のインターフェイスとクラス）

名称は最初から型クラス(type classes)です。いわゆるオブジェクト指向言語のインタフェースとは見た目は似ているかもしれませんが実際には大きく違っています。

> 共通のメソッドを提供する型の集合（オブジェクト指向のクラスではない！）

型がメソッドを提供している(=直接持っている)わけではないことに気をつけてください。型自体はメソッドの存在を知りません。あくまでも、型の外で型とメソッドの関係を管理している部分があり、それがinstance宣言された型に応じてメソッドをディスパッチさせています。繰り返しますが、**オブジェクト指向のインタフェースとは似て非なる**ものです。

> 型クラスの中でもっとも重要なモナドという概念がある！（のちに説明）

型クラスとしてはそこまで重要ではありません。モナドは簡単に言ってしまえば、自分自身が持つ値を書き換える仕組みを何らかのコンテナに対して提供するものです。何かしらをモナドとして実装する場合は、色々と注意が必要です(一定の抽象化能力も必要とします)。モナドについて書く前に調べておきましょう。また、無理にモナドにせずとも解決できる部分が割とあったりします。(話し始めるなら、同じタイミングで説明しちゃった方がいいかと…)

### 条件分岐

> 分岐（オブジェクト指向のif文）
条件式で表す
    文法 : if [条件1] else [結果1] else [ 結果2]
    例：abs n = if n => 0 then n else - n
ガード付き等式
    文法 : | [条件1] = [結果1]
       　　| [条件2] = [結果2]
    例：abs n | n => 0 = n
          　　| otherwise = - n

* if 式は `if [条件式] then [真の場合] else [偽の場合]` です。
* 比較するのであれば`>=`を使ってください(`=>`は型クラス制約の注釈です)
* **文じゃない**よ！

取り急ぎ。(まだ出てくるかも…)

**Comment by func-hs** [comment]
### 言語間での言葉の意味やニュアンスの違いに注意

後、ComparisonJava.md についてですが、間違いというよりは、齟齬が発生しやすいという点でもいくつか気になるところがありました。特に…

* クラス・メソッド定義
* 列挙型
* インスタンス・メソッド呼び出し

上の3つは気をつけてください。例えばクラス・メソッドだと、JavaやC++に慣れた側からすると、staticメソッドを連想されるかもしれませんし、インスタンス・メソッドも同様にmemberメソッドを連想されるかもしれません。列挙型についても、Java、C++、そしてHaskellとでそれぞれ実態が違っています。同じだと話してしまわないように注意してください。また、Haskellはあくまで代数的データ型の1記法として列挙体風なものが存在しているだけということにも注意してください。

> (型間の継承はない)
(抽象クラスとそれを継承するクラスのようにも見える例)
data Shape = Circle Int Int Int | Rectangle Int Int Int Int

ないものは無理して書かない方が吉です。混乱を招きやすいので。

**Comment by func-hs** [comment]
> 抽象データ型
(LeafとNodeがモジュールの外から見えず，別の関数で生成する場合)
data Tree a=Leaf|Node a a
makeTree :: [a] -> Tree a
makeTree = ~

*モジュールの外から見えず* というのがよくわかりません。また、`Leaf` と `Node a a` はデータコンストラクタとして成立しているので、基本的にどこからでもこれらのコンストラクタでTree型を生成できます。(ところで、Leafの方には型というか値差し込まなくてよいのです…？)

**Comment by func-hs** [comment]
### Environment.md

> 環境構築について
Haskell PlatformをDLするのが楽

確かに楽ですが、Haskell Platformは標準で抱え込んでいるライブラリのバージョンが固定されているので、そのバージョンから外れたものに依存しているパッケージをインストールしようとすると、**コンフリクト**しはじめます。注意が必要です。GHCだけ落として、必要に応じてパッケージを入れるのがベターかもしれません。
*(初学者向けのもので OpenGL だとか Win32API だとかは必要にならないかと思われます)*

**Comment by func-hs** [comment]
## FunctionalProgramming.md

> 副作用って？
関数:数学の関数ととらえ、周囲の状態を変更してしまうこと

周囲の状態を変更することもそうですが、その関数の返り値が周囲から影響を受けることも含まれます。更に言うと、**引数に対して返り値が一意に定まらなくなる要因を含む計算や、それを引き起こしやすいデータ構造**は全般的にそう呼ぶことができます。代表的なものは概ね以下のとおりです。

* IO (真に副作用と呼べるのはこの IO だけだという話もあります)
* 乱数生成 (当然ながら呼び出すたびに違う結果が返ってきます)
* ネットワーク (呼び出すタイミングによっては違う結果が返ってきたり、最悪繋がらなかったりします)
* 失敗可能性 (いわゆる Maybe のことです。所定の計算の結果が結果として認められない場合などなど、Nothing を返させて安全に異常を落としたりします)
* Either (片側を例外のコンテナとみなしてハンドリングしていくのが常套手段になってます)
* 非決定性計算 (List のことです。これは、**終端が一意に定まっているとは限らない**ことを意味しています)

数学の関数としてではなく、**プログラムのコードや命令として一意性を妨げる要因が何かがポイント**です

**Comment by func-hs** [comment]
> 関数型言語
「プログラム」 を 「関数」 のみで考える。
ということは？
>
> メモリ確保をしなくてもいい！！

いいえ。確かに私達サードパーティ側が直接 malloc したり new したりといったことはあまり必要ない言語ではありますが…**メモリ確保自体が不要になったわけではない**ことに注意してください。

> インスタンスを生成しなくてもいい！（newとかしなくていいよ～）

式中に使用するデータコンストラクタがいわゆる new みたいなものですね。上の指摘と被るのですが、コード上から直接メモリ確保するための構文が隠されただけで、メモリ自体は普通に確保・消費されます。

> 設計の概念が違う！→ 関数がファーストクラス！

先駆けにはなりましたが、今ではC++でもJavaでもラムダ式という形でファーストクラス(もしくはそれに限りなく近い扱いの)オブジェクトになってますね。

> 関数型言語の特徴
- λ式
- 高階関数
- カリー化

他にもあると思うナ〜

> λ式（無名関数）
並列処理を書くときに効果絶大らしい！

いいえ(･ω･)

**Comment by func-hs** [comment]
とりあえず、現状で指摘できるのはこんなところですかね…。

どうせやるのですから、実用への到達を前提に、良い評価を得たいですね。

応援してます :)

**Comment by sogiSpk** [comment]
すみません。

今気づきました。
ご指摘ありがとうございます。
もう発表は終わりましたが、指摘の内容など大変ありがたいので、勉強しなおす材料にします。
